### ISSUE TITLE
Accelerometer  Parameter

### ISSUE THREAD

**Issue by jacklu333333** [stm32duino/LSM6DSL#11]
Hi, I perform some experiments with this module to test the accuracy by putting it on a desk and see the X-Axis, Y-Axis, which should be 0. And I found out that the result is quite amazing with an average almost equal to 0 and a small standard deviation for 10000 continuous points.

However, for sensitivity mode +-2g, the sensitivity constant you set up is 0.6 and then you use int32_t as the variable type. So I perform another experiment with the sensor by getting the raw data and compute later with float type.

It makes sense to have a larger standard deviation since you guys round it up when using the int32_t type variable. Yet, the code you guys have is also much more accurate since it is more close to 0.

I was wondering why you set up the constant as 0.6 rather then 1000/2^14 and also why you choose the variable for int32_t rather than float because with this combination, the accuracy raises a lot?

Thanks

**Comment by cparata** [comment]
Hi @jacklu333333 ,
actually, I just implemented the datasheet specifications:

https://www.st.com/resource/en/datasheet/lsm6dsl.pdf

Basically at page 21, you can find the sensitivity for every full scale (for example 0.061 for +/-2g full scale). The choice of the int32_t vector for the Get_X_Axes was just an implementation choice. Anyway, if you need more accuracy, you can always manage a float vector output with a piece of code like this:

```
int16_t accelerometer_raw[3];
float sensitivity;
float accelerometer_float[3];

AccGyr->Get_X_AxesRaw(accelerometer_raw);
AccGyr->Get_X_Sensitivity(&sensitivity);

accelerometer_float[0] = sensitivity * (float)accelerometer_raw[0];
accelerometer_float[1] = sensitivity * (float)accelerometer_raw[1];
accelerometer_float[2] = sensitivity * (float)accelerometer_raw[2];

```
Best Regards,
Carlo
