### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dacattack** [stm32duino/LSM6DSL#14]
Hi, 
I tried to compile the example DISCO_IOT_LSM6DSL_DataLog_Terminal or any other on my arduino UNO board  and always shows up the same error:

no matching function for call to 'TwoWire::TwoWire(const uint8_t&, const uint8_t&)'
It also says:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:5: note: candidate: TwoWire::TwoWire()
     TwoWire();
     ^~~~~~~
C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:5: note:   candidate expects 0 arguments, 2 provided
C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:34:7: note: candidate: constexpr TwoWire::TwoWire(const TwoWire&)
 class TwoWire : public Stream
       ^~~~~~~
C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:34:7: note:   candidate expects 1 argument, 2 provided
C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:34:7: note: candidate: constexpr TwoWire::TwoWire(TwoWire&&)
C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:34:7: note:   candidate expects 1 argument, 2 provided

I have no idea how to fix it. I've tried to search about it but i did not found anything. I need to fix this issue for a job work.
Thanks in advance.

**Comment by cparata** [comment]
Hi @dacattack ,
what is the board with the LSM6DSL that you are using with the Arduino UNO? You can try commenting lines 46, 47 and 50 and replacing them with:

`#define dev_i2c Wire`

According your hardware, you could also need to change the I2C address on line 51. So, if LSM6DSL_ACC_GYRO_I2C_ADDRESS_LOW does not work in your case, you can try:

`LSM6DSLSensor AccGyr(&dev_i2c, LSM6DSL_ACC_GYRO_I2C_ADDRESS_HIGH);`

Best Regards,
Carlo

**Comment by dacattack** [comment]
Thanks very much for your comment. I'm using the arduino UNO board. Now I have no errors at compiling but yet i have a question. Since we've commented the SDA,SCL pin assignment :
//#define I2C_SDA A4
//#define I2C_SCL A5
//TwoWire dev_i2c(I2C_SDA, I2C_SCL);
and instead I've used the:
#define dev_i2c Wire
What are the I2c pins now assigned? A4 and A5 by default ??

**Comment by cparata** [comment]
Hello @dacattack ,
the "Wire" instance uses the default I2C pins of the Arduino UNO that are SCL and SDA.
Best Regards,
Carlo

**Comment by dacattack** [comment]
Indeed, you are right. Just in case it does not bother you. I'm not an expert on the deepest level of c++(neither I master c++ at all, I've been working with c pretty much) of the arduino firmware. Could you explain to me why commenting those lines and adding the #define dev_i2c Wire it worked?
And what Wire is? an object?
Appreciatively,
DACattack.

**Comment by cparata** [comment]
Hi @dacattack ,
I guess that the constructor TwoWire(I2C_SDA, I2C_SCL) is available only on STM32duino Core but not in the Arduino UNO Core. Consider that the example that you are trying to use is targeting the Disco IoT board that is an STM32 based board. So, it was not written for Arduino UNO. "Wire" is the default I2C class instance in Arduino and it should be available in both cores and so it worked also for Arduino UNO board. If you search it in the Arduino UNO Core source code you will find that the "Wire" is defined as:

`TwoWire Wire = TwoWire();`

Best Regards,
Carlo

**Comment by dacattack** [comment]
Hello again.
I just want to thank you again for all your soport.
The only problem I still have is related with the interruptions. I can't
get it to work.
For example in the double tap or 6D orientation examples, I've tried to add
to the function  in the setup that enables the double tap detection (or the
6D orientation) the pin that will be set as the interruption  input inside
the said functions arguments.
However it didn't work too.
So far I've only been able to get to work  the data terminal log example.
Best regards,
Dacattack.

**Comment by cparata** [comment]
Hello @dacattack ,
unfortunately, not all digital pins can be used as interrupt on Arduino boards. On STM32 based boards, instead, basically whatever digital or analog pin can be used as interrupt. You can find [here](https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/) the list of the pins that can be used as interrupt on Arduino UNO. Basically, the only solution for you is to connect with a wire the LSM6DSL interrupt pin to one between pins 2 or 3 of the Arduino UNO and adapt accordingly the sketch code.
Best Regards,
Carlo

**Comment by dacattack** [comment]
Hello @Carlo,
my apologies for such a trivial question.  Indeed the only pins allowed are 2 and 3 in my UNO board. Now the double tap works perfectly. However I'm still struggling to get the 6D orientation code to work. I think I've made all the  relevant changes to make it work. I'll attach the  code as a  file text
[6D_ORIENT.TXT](https://github.com/stm32duino/LSM6DSL/files/8728043/6D_ORIENT.TXT)
.

**Comment by cparata** [comment]
Mmmmhhhh, this is really strange because the mechanism for the interrupt of 6D orientation is the same of the Double Tap. So, if the Double Tap works on your side also the 6D Orientation must work. Maybe, it could be an issue of memory (a vector of 256 byte could be too big for Arduino Uno). Try, for example, to change the output string in something like Position 1, Position 2, ... , Position 6 using just a vector of 20 bytes.
