### ISSUE TITLE
reading accelerometer

### ISSUE THREAD

**Issue by droussel3** [stm32duino/LSM6DSL#8]
Hello
i would like to use gyroscope with x translation
So i try to convert measure in mdps with something like reading = accelerometer.get_x()

Thank you

**Comment by fpistm** [comment]
@cparata could you help @droussel3 ?

**Comment by cparata** [comment]
Hi,
it is not clear to me what do you want to do. You already have the values of the gyroscope in mdps. As written in the readme.txt you just need to enable the gyroscope (AccGyr->Enable_G()) and then read the values of the gyroscope (AccGyr->Get_G_Axes(gyroscope)). The "gyroscope" variable is a vector with 3 components where you can find respectively the values of the x, y, z components of the gyroscope expressed in mdps.
Regards,
Carlo

**Comment by droussel3** [comment]
hi
it is not totaly clear for me..
but for the moment i update the core (2017.11.24) and i have non values with the message

ERROR: at least one I2C pin has no peripheral
Acc[mg]: 0 0 0 | Gyr[mdps]: 0 0 0
Acc[mg]: 0 0 0 | Gyr[mdps]: 0 0 0

the last core (2018) make errors for all library.

Thanks

**Comment by cparata** [comment]
Which board are you using? The examples that you can find in the LSM6DSL library work only with B-L475E-IOT01A board. In fact in order to use this library you need a board that mounts the LSM6DSL component. Another possibility is to use a Nucleo board plus the X-NUCLEO-IKS01A2 expansion board. In this last case you need to download LSM6DSL, HTS221, LPS22HB, LSM303AGR and X-NUCLEO-IKS01A2 libraries and use the examples that you can find in the X-NUCLEO-IKS01A2 library.
Regards,
Carlo

**Comment by droussel3** [comment]
Hi @cparata 

excuse me for long time but i have a problem with the next update core (1.1.1). 
Every thing was wrong
i put now 1.1.0 and all is good.
so now i try to understand why i find mesure 
Gyr[mdps]: 770 -2380 2100
it seems to be millidegrés and why 2100 ?
thanks

**Comment by fpistm** [comment]
Just a quick not about core version.
1.1.1 is not a new one it is only the 2018.1.18 version.
For project needs, the version have been moved from date to semantic versioning:
https://github.com/stm32duino/wiki/wiki/Release-Versioning-change

**Comment by cparata** [comment]
Hi @droussel3 
the output of the gyroscope is expressed as angular speed in millidegrees per second. In the example, that you posted, the three values are the components of the angular speed (that is a vector quantity) respectively on the x, y and z axis. If you check in the datasheet of the LSM6DSL (http://www.st.com/content/ccc/resource/technical/document/datasheet/ee/23/a0/dc/1d/68/45/52/DM00237456.pdf/files/DM00237456.pdf/jcr:content/translations/en.DM00237456.pdf) you can find that the angular rate zero-rate level is +/- 3dps that is +/- 3000mdps (page 21 of the datasheet). This value indicates the deviation of an actual output signal from the ideal output signal if no movement is present. So, the values of the gyroscope, that you can see when the board is still, are perfectly aligned to the specs of the component. So if you agree, I would close this issue.
Regards,
Carlo
